# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Patrick Taylor
email: hello@patricktayloredwards.com
description: > # this means to ignore newlines
  Portfolio
url: http://patricktayloredwards.com/
facebook_username: patricktayloredwards
github_username:  01taylop
twitter_username: patchfalcon

# Build settings
markdown: kramdown
highlighter: rouge
