# Site settings
title: Patrick Taylor
description: Portfolio of Patrick Taylor, a London-based software engineer at Expedia.
email: hello@patricktaylor.dev
locale: en_GB
social:
  - name: GitHub
    url: https://github.com/01taylop/
  - name: Instagram
    url: https://www.instagram.com/01taylop/
  - name: LinkedIn
    url: https://www.linkedin.com/in/patrick-taylor1/
  - name: Stack Overflow
    url: https://stackoverflow.com/users/1359306/patrick
url: https://patricktaylor.dev

# Build settings
exclude:
  - package.json
  - README.md
  - yarn.lock
highlighter: rouge
markdown: kramdown
permalink: pretty
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
timezone: Europe/London
